title: Evan Hanif Widiatama
logo: /assets/img/circleprofile.png
description: AI Engineer | Computer Vision, ML & Backend
# show_downloads: true
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
